config/routes.rb
Rails.application.routes.draw do
  
 resources :users, only: [:new, :create, :articles]
  
  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  get 'welcome', to: 'sessions#welcome'

  get 'authorized', to: 'sessions#page_requires_login'

  delete 'logout' => 'sessions#destroy'

  post 'user', to: 'users#users'

  get 'home/index'

  # resource method can be used to declare a standart REST resource
  # you need to add the article resource to the config/routes.rb so the file will look as follows
  
  resources :articles do
    # this create comments as a nested resource with articles
    resources :comments
  end
  
  post "searching" => 'home#searching'

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :commenter, presence: true, length: { minimum: 3}
  validates :body, presence: true, length: { minimum: 10}
  
end

app/models/country.rb
class Country < ApplicationRecord
# atributes that created by defaul for ActiveRecord model: 
# id, created_at, updated_at 
# Country.column_names - view the information of the atributes of the class Country 

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of :username
  validates_uniqueness_of :username
  attribute :role, :string, default: 'user'
  has_many :aticles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
    helper_method :logged_in?
    helper_method :current_user
    
    
    def current_user   
        User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?  
    end

    def authorized
      #  redirect_to '/welcome' unless logged_in?
     end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# To save data we need create here some logic

class ArticlesController < ApplicationController
  
  $comment_form_hidden = false

  # здесь описаны екшены которые срабатывают автоматически при  
  def index

    if params.has_key? :search
      @search = params[:search]
      @articles = Article.where("lower(title) like ?", "%#{@search.downcase}%")
      if @articles.size < 1 
        @articles = Article.where("lower(text) like ?", "%#{@search.downcase}%")
      end
    else
        @articles = Article.all
      end
  end
  
  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end


  def create
    @user_id = session[:id]
    
    @article = @user.articles.create(article_params)
     #@article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
   end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
     end
  end

  def destroy
    #  проверка перед удалением на ошибки 

    @article = Article.find(params[:id])
    if  @article.errors.present?
      throw(:abort) 
    else
      @article.destroy
      redirect_to articles_path
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
  
  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/example_controller.rb
class ExampleController < ApplicationController
  def test
    @current_time = Time.now
    @foo = "Hi, I'm foo variable"
  end
  def index
    @foo = "Hi, I'm foo variable twice"
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    # used to goes to tje sites and collects data
    require 'net/http'
    # pass that data once we collected and bring it back to our app
    require 'json'

    # API url
    $API_KEY = 'api_key=f86cc31e3850cd90ef8e189703f28ac1'
    $DOMEN = 'https://api.themoviedb.org/3/'
    $IMG_URL = 'https://image.tmdb.org/t/p/w500'

    $top_rated = 'movie/top_rated?'
    $popular_movies = 'movie/popular?'
    $SEARCH = 'search/movie?'

    # fetching new films
    def fetch_films(url)
      @url = url
      # uniform resource indicator - URL type thing
      @uri = URI(@url)
      @response = Net::HTTP.get(@uri)
      @output = JSON.parse(@response)
    end

    # render films on the page
    def render_films(output_request)
      @output = output_request
      if @output['results'].empty?
        @error_on_request = 'Error nothing to render here'
      else
        render 'home/_card'
      end
    end

    def get_popular_films
      @url = $DOMEN + $popular_movies + $API_KEY
      @result = fetch_films(@url)
      render_films(@result)
      # the way to show the JSON on page
      # @output_JSON = @result
    end

    get_popular_films

    def searching
      @film_name = params[:search_request]
      if params[:top_films] == ''
        @film_name = 'Films is not found!'
      else
        @url = $DOMEN + $SEARCH + $API_KEY + '&query=' + @film_name.to_s
        @result = fetch_films(@url)
        render_films(@result)
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :authorized, only: [:new, :create, :welcome]
  
  def new
  end

  def create
    # use to 
    user = User
    .find_by(username: params[:username])
   # .try(:authenticate, params["username"]["password"]

    if user && user.authenticate(params[:password])
        session[:user_id] = user.id 
        redirect_to '/welcome'
    else
      flash[:danger] = 'Invalid user/password combination'
      render 'new'
    end
  end

  def welcome
    
  end

  def login
  end

  def page_requires_login
  end
  
  def destroy
    session.delete(:user_id)
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authorized, only: [:new, :create]

   def show
    @user = User.find(params[:id])
  end

  def new

    @user = User.new

  end

  def create
    @user = User.create!(params.require(:user).permit(:username, :password))

    session[:user_id]= @user.id
    if @user
        redirect_to '/welcome'
    else
      redirect_to '/users/new'
    end
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/example_helper.rb
module ExampleHelper
    def render_stars(value)
        output = ''
        if (1..5).include?(value)
            value.times { output += '*' }
        end
        output
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%#= form_with(model: @article, local: true) do |form| %>
<%= form_with(model: [@user, @article ], method: "get", local: true) do |form| %>

<% if @article.errors.any? %>
<div class="alert alert-danger" id="error_explanation" role="alert">
  <h2>
    <%= pluralize(@article.errors.count, "error") %> prohibited
    this article from being saved:
  </h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="card-body text-white">
  <%= form.label :title %>
  <%= form.text_field :title, class: "form-control" %>
</div>

<div class="card-body text-white">
  <%= form.label :text %>
  <%= form.text_area :text, class: "form-control" %>
</div>

<div class="card-body">
  <%= submit_tag 'Submit', class: 'btn btn-primary' %>
  <%= link_to  "Back", articles_path,  class: "btn btn-secondary" %>
</div>
<% end %>

app/views/articles/_pagination.html.erb
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
    <li class="page-item active"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
  </ul>
</nav>

app/views/articles/edit.html.erb
<div class="card text-white bg-info m-auto" style="min-width: 22rem;">

  <h5 class="card-header"> Edit Article № <%= @article.id %></h5>

  <%= render 'form' %>

</div>

app/views/articles/index.html.erb
    <form>
        <div class="form-row ">
            <%= form_with(url: articles_path, method: "get", local: true) do |form| %>
            <div> <%= form.text_field :search, :value => @search, autofocus: true, placeholder: "Search by title", class: "form-control mr-sm-2"%></div>
            <div> <%= form.submit "Search", :name => "", class: "btn btn-outline-primary my-2 my-sm-0" %></div>
            <% end %>
            <% if logged_in? %>
            <div class="col-auto"><%= link_to 'New Article', new_article_path, class: "btn btn-success"%></div>
            <% end %>
        </div>
    </form>
    <table class="table mt-2">
        <tr>
            <th scope="col">id</th>
            <th scope="col">Label</th>
            <th scope="col">Text</th>
            <th scope="col">Comment</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>

        <% @articles.sort.each do |article| %>
        <tr>
            <th scope="row"><%= article.id %></th>
            <td><b><%= link_to article.title, article_path(article) %></b></td>
            <td><%= link_to article.text, article_path(article) %></td>
            <td><%= article.comments.size %></td>
            <% if logged_in? %>
            <td><%= link_to 'Edit', edit_article_path(article), class: "btn btn-info" %></td>
            <td><%= link_to 'x', article_path(article),
   method: :delete,
   data: { confirm: 'Are you sure?'},
   class: "btn btn-danger" %></td>
            <% else %>
            <td></td>
            <td></td>
            <% end %>
        </tr>
        <% end %>
    </table>

    <% if false then %>
    <%= render  "articles/pagination" %>
    <% end %>

app/views/articles/new.html.erb
<div class="card text-white bg-info m-auto" style="max-width: 25rem;">
  
  <h5 class="card-header">New article</h5>

  <%= render 'form' %>

  </div>

app/views/articles/show.html.erb
<div class="card bg-light m-auto" style="min-width: 22rem;">

    <div class="card-header">Article № <%= @article.id %></div>

    <div class="card-body">
        <h5 class="card-title">Title:
            <%= @article.title %>
        </h5>
        <p class="card-text">Text:
            <%= @article.text %>
        </p>
        <div class="mb-2">
            <% if !current_user.nil?  then %>
            <%= link_to  "Delete", article_path(@article),
   method: :delete,
   data: { confirm: 'Are you sure?'},
   class: "btn btn-danger" %>
            <%= link_to  "Edit", edit_article_path(@article), class: "btn btn-info" %>
            <% end %>
            <%= link_to  "View All", articles_path, class: "btn btn-secondary" %>
        </div>

        <% if !@article.comments.empty?  then %>
        <div class="card m-auto">
            <div class="card-header bg-info">Comments</div>
            <%= render @article.comments %>
        </div>
        <% end %>
        <% if !current_user.nil?  then %>
        <%= render 'comments/form' %>
        <% end %>

    </div>
</div>

app/views/comments/_comment.html.erb
  <div class="card">
    <div class="card-header"> <b> @<%= comment.commenter %>
      </b>
      <%= comment.created_at.strftime(" %m.%d.%Y") %>
    </div>
    <div class="card-body">

      <div class="card-text border-success">
        <%= comment.body %>
      </div>
      <br />
      <% if !current_user.nil?  then %>
      <%= link_to 'Remove', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' },
               class: "btn btn-danger card-link" %>
      <% end %>
    </div>
  </div>

app/views/comments/_form.html.erb
<div class="card border-success mb-3">
  <div class="card-header bg-success"> Add a comment:</div>

  <%= form_with(model: [@article, @article.comments.build ], local: true ) do |form| %>

  <div class="card-body">
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter, value: (current_user.nil? ? 'default' : current_user.username), class: "form-control" %>
  </div>
  <div class="card-body">
    <%= form.label :body %><br>
    <%= form.text_area :body, class: "form-control" %>
  </div>
  <div class="card-body">
    <%= submit_tag 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>

</div>

app/views/example/test.html.erb
<h1>Example</h1>
<p>Find me in app/views/example/test.html.erb</p>
<br />
<p> Addition:
    <% (0..5).each do |i| %>
    <%= "#{i}, " %>
    <% end %>
</p>
<section>
    The current time is:
    <%= @current_time %>
</section>
<%# = render partial: "shared/footer", locals: {start_year: '2001'} %>
<%= render partial: "shared/footer" %>

<p>
    <b> Rating: </b> <%=render_stars(5) %>
</p>
<%= debug @foo %>
<%console %>

app/views/home/_card.html.erb
 <% @output['results'].each do |film| %>
 <div class="card m-3" style="width: 20rem;">
     <img class="card-img-top" src="<%= $IMG_URL + film['poster_path'].to_s   %>" alt="Card image cap">
     <div class="card-body">
         <h5 class="card-title"><%= film['title'] %></h5>
         <hr class="my-4">
         <h5 class="card-text">Rating: <b><%= film['vote_average'] %></b></h5>
         <p class="card-text"><%= film['overview'] %></p>
         <p class="card-text">Date release: <%= film['release_date'] %></p>
         <a href="<%= @button_url= $DOMEN + 'movie/' + film['id'].to_s + '?' +$API_KEY %>" class="btn btn-primary ">Details</a>
     </div>
 </div>
 <% end %>

app/views/home/_container.html.erb
<div class="jumbotron alert-danger">
    <h3 class="display-5">Stay at home and away from others, Coronavirus here! 🦠😷</h3>
    <p class="lead">You can spread the virus even if you don’t have symptoms.</p>
    <hr class="my-4">
    <p> What youre need to know: </p>
    <ul>
        <li>Only go outside for food, health reasons or work (but only if you cannot work from home)</li>
        <li>If you go out, stay 2 metres (6ft) away from other people at all times</li>
        <li>Wash your hands as soon as you get home</li>
        <li>Do not meet others, even friends or family.</li>
        <ul>
        <%# if you wanna to see the JSON answer uncomment %>
        <%# @output_JSON %>
</div>

app/views/home/_footer.html.erb
	<footer>
	    <div>
	        Coded and built with
	        <span role='img' aria-label='heart'>
	            ❤️
	        </span>
	        by
	        <a href='https://www.linkedin.com/in/synkevych' target='_blank' rel='noopener noreferrer'>
	            Synkevych
	        </a>
	    </div>
	    Source code available on
	    <a href='https://github.com/Synkevych/top_films_on_rails' target='_blank' rel='noopener noreferrer'>
	        GitHub
	    </a>
	</footer>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Top Rated Movies </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/home">Top Films</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/articles">Articles</a>
            </li>
        </ul>
        <%= form_tag searching_path, :method => 'POST' do %>
        <div class="form-inline my-2 my-lg-0">
            <%= text_field_tag 'search_request', nil, placeholder: "Search Film", class: "form-control mr-sm-2" %>
            <%= submit_tag 'Search', class: 'btn btn-secondary mr-2 '%>
            <% end %>

            <% if !current_user.nil? %>
            <%= button_to current_user.username, '/user', :method=> 'GET', class: 'btn btn-success my-2 my-sm-0'%>
            <% else %>
            <%= button_to 'Login', '/login', class: 'btn btn-success my-2 my-sm-0'%>
            <% end %>
        </div>
</nav>

app/views/home/_pagination.html.erb
<nav aria-label="navigation">
    <ul class="pagination justify-content-center">
        <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        <li class="page-item active"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>

app/views/home/index.html.erb
    <div class="container">
      <%= render 'home/container' %>
      <%# @output_JSON %>
      <div class="row mx-auto">
        <%= yield %>
      </div>
      <% = render 'home/pagination'%>
    </div>

app/views/home/searching.html.erb
<br />
<h5> You are searching: <%= @film_name %>
</h5>

app/views/home/top_films.html.erb
<br />
<h5> You are searching: <%= @film_name %>
</h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Top Rated Movies</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'home/navbar' %>
  <div class="container">
    <br>
    <div class="row mx-auto">
    <%= yield %>
    </div>
  </div>
  <%= render 'home/footer' %>
</body>

</html>

app/views/shared/_footer.html.erb
<hr>
<p>
    Copyright
    <%= "#{start_year} - " if defined? start_year %>
    <%= Date.today.year %>
    the Easter Bunny.
</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sing Up</h1>
<p>Find me in app/views/users/new.html.erb</p>



<%= form_for @user do |form| %>
<%= form.label :username %><br>
<%= form.text_field :username %><br>

<%= form.label :password %><br>
<%= form.password_field :password %><br>
<%= form.submit %>
<%= button_to "Login", '/users/new', method: :get%>

<% end %>

app/views/users/users.html.erb
<div class="jumbotron">
    <h3 class="display-5">User:</h3>
    <p class="lead">
        <%if logged_in?%>
        You are Logged In, <b><%= current_user.username %></b>
        <%end%></p>
    <hr class="my-4">
    <p> Change name: </p>
    <ul>
        <li><%= button_to "Change name", '/create', method: :get%></li>
        <li><%= button_to "Logout", '/logout', method: :delete%></li>
        <ul>
</div>